name: Docfx
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'OperatorsForGenericGenerator/**'

jobs:
  docfx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nikeee/docfx-action@v1.0.0
      name: docfx
      with:
        args: OperatorsForGenericGenerator/docfx.json
    - uses: maxheld83/ghpages@master
      name: gh-pages publish
      env:
        BUILD_DIR: OperatorsForGenericGenerator/_site
        GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
